"""Typed request and response schemas for SatQuery queries."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator

from backend.schemas.common import AnalysisEvidence, AnalysisVisualization
from backend.schemas.query_understanding import StructuredQuery
from backend.schemas.router import RoutingDecision
from backend.schemas.tool import ToolResult


class ExecutionTraceStep(BaseModel):
    """Single step in the agent execution trace."""

    step: int = Field(..., description="1-indexed step number")
    action: str = Field(..., description="Action name, e.g. 'Query Understanding'")
    detail: str = Field(..., description="Detailed description of step output or action")
    duration_ms: Optional[float] = Field(default=None, description="Step duration in milliseconds")
    status: str = Field(default="completed", description="Execution status: completed | skipped | failed")


class QueryRequest(BaseModel):
    """Incoming query request model."""

    query: str = Field(
        ...,
        description="Natural language question or instruction for remote sensing analysis.",
        examples=["What objects are present in this image?"],
    )
    before_image: Optional[str] = Field(
        default=None,
        description="Path, URI, or base64 string for baseline (T1) satellite image.",
        examples=["tests/data/sat_before.jpg"],
    )
    after_image: Optional[str] = Field(
        default=None,
        description="Path, URI, or base64 string for follow-up (T2) satellite image.",
        examples=["tests/data/sat_after.jpg"],
    )
    before_image_modality: Optional[str] = Field(
        default=None,
        description="Optional sensor modality for baseline image ('optical' | 'sar' | 'unknown').",
    )
    after_image_modality: Optional[str] = Field(
        default=None,
        description="Optional sensor modality for follow-up image ('optical' | 'sar' | 'unknown').",
    )
    parameters: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional tool-specific execution parameters (e.g. sensitivity, coregistration_threshold).",
    )

    @field_validator("query")
    @classmethod
    def validate_query_not_empty(cls, v: str) -> str:
        """Ensure the query is not empty or pure whitespace."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("Query string cannot be empty or contain only whitespace.")
        return stripped


class QueryResponse(BaseModel):
    """
    Response model for SatQuery queries.

    In Block 1 (Foundation), returns the received query and processing status.
    Typed fields are pre-structured for seamless agent pipeline integration in subsequent blocks.
    """

    received_query: str = Field(
        ...,
        description="The query string received and validated by the backend.",
    )
    status: str = Field(
        default="received",
        description="Current processing status (e.g. 'received', 'in_progress', 'completed', 'failed').",
    )

    # Pre-structured fields for agent orchestration integration (Block 2+)
    analysis_id: Optional[str] = Field(
        default=None,
        description="Unique identifier for tracking the analysis session.",
    )
    task: Optional[str] = Field(
        default=None,
        description="Classified capability or task (e.g. 'vqa', 'grounding', 'change_detection').",
    )
    answer: Optional[str] = Field(
        default=None,
        description="Reasoned textual answer generated by the agent.",
    )
    confidence: Optional[float] = Field(
        default=None,
        description="Estimated confidence score between 0.0 and 1.0.",
    )
    evidence: List[AnalysisEvidence] = Field(
        default_factory=list,
        description="Grounded evidence items supporting the answer.",
    )
    visualizations: List[AnalysisVisualization] = Field(
        default_factory=list,
        description="Visual overlays, bounding boxes, or masks.",
    )
    execution_trace: List[ExecutionTraceStep] = Field(
        default_factory=list,
        description="Transparent step-by-step trace of agent execution.",
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Informational warnings or caveats regarding imagery/inference.",
    )
    structured_query: Optional[StructuredQuery] = Field(
        default=None,
        description="Detailed structured parameters extracted by the Query Understanding intelligence layer.",
    )
    routing_decision: Optional[RoutingDecision] = Field(
        default=None,
        description="Structured tool selection decision produced by the Agent Router.",
    )
    tool_result: Optional[ToolResult] = Field(
        default=None,
        description="Structured execution result returned by the selected specialist tool.",
    )
