"""Schemas for SatQuery Tool Execution and Tool Results."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from backend.schemas.common import AnalysisEvidence, AnalysisVisualization


class ToolStatus(str, Enum):
    """Execution status returned by tools."""

    NOT_IMPLEMENTED = "not_implemented"
    COMPLETED = "completed"
    CLARIFICATION_NEEDED = "clarification_needed"
    ERROR = "error"


class ToolResult(BaseModel):
    """
    Structured result returned by any specialist tool or clarification handler.
    Guarantees consistent output contract across all tools.
    """

    tool_name: str = Field(..., description="Name or identifier of the executed tool")
    status: str = Field(
        ...,
        description="Execution status: 'not_implemented', 'completed', 'clarification_needed', 'error'",
        examples=["not_implemented", "completed", "clarification_needed", "error"],
    )
    answer: Optional[str] = Field(
        default=None,
        description="Generated answer or clarification message. None for placeholder tools.",
    )
    confidence: Optional[float] = Field(
        default=None,
        description="Confidence score of tool execution, if applicable.",
    )
    evidence: List[AnalysisEvidence] = Field(
        default_factory=list,
        description="Analytical evidence items generated by the tool.",
    )
    visualizations: List[AnalysisVisualization] = Field(
        default_factory=list,
        description="Visual assets (e.g. bounding boxes, masks, overlays) generated by the tool.",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Tool execution metadata, sensor details, or diagnostic parameters.",
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Informational warnings, caveats, or error messages from the tool.",
    )
